<?php

namespace Rizbo\SymfonyTracer;

use Symfony\Component\Config\Definition\Configurator\DefinitionConfigurator;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\AbstractBundle;

class SymfonyTracerBundle extends AbstractBundle
{
    public function configure(DefinitionConfigurator $definition): void
    {
        parent::configure($definition); // TODO: Change the autogenerated stub
    }

    public function loadExtension(array $config, ContainerConfigurator $container, ContainerBuilder $builder): void
    {
        dump($config);
    }
}